//Author
export const FETCH_ALL_AUTHOR = "FETCH_ALL_AUTHOR";
export const GET_DETAIL_AUTHOR = "GET_DETAIL_AUTHOR";
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE AUTHOR";

//Book
export const FETCH_ALL_BOOK = "FETCH_ALL_BOOK";
export const FETCH_BOOK_TRENDING = "FETCH_BOOK_TRENDING";
export const GET_BOOK_BY_FILTER = "GET_BOOK_BY_FILTER";
export const GET_DETAIL_BOOK = "GET_DETAIL_BOOK";
export const CREATE_BOOK = "CREATE_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE BOOK";

//Category
export const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE CATEGORY";

//Authentication
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_STATE_FROM_LOCAL = "SET_STATE_FROM_LOCAL";
export const REGISTER = "REGISTER";
export const UPDATE_USER = "UPDATE_USER";

//Cart
export const ADD_BOOK_IN_CART = "ADD_BOOK_IN_CART";
export const GET_BOOK_IN_CART = "GET_BOOK_IN_CART";
export const UPDATE_BOOK_IN_CART = "UPDATE_BOOK_IN_CART";
export const DELETE_BOOK_IN_CART = "DELETE_BOOK_IN_CART";

//Wishlist
export const ADD_BOOK_IN_WISHLIST = "ADD_BOOK_IN_WISHLIST";
export const GET_BOOK_IN_WISHLIST = "GET_BOOK_IN_WISHLIST";
export const DELETE_BOOK_IN_WISHLIST = "DELETE_BOOK_IN_WISHLIST";

//Order
export const PLACE_ORDER = "PLACE_ORDER";

//HOC FORM ADMIN
export const MODALFORM_ADD_AUTHOR = "MODALFORM_ADD_AUTHOR";
export const MODALFORM_EDIT_AUTHOR = "MODALFORM_EDIT_AUTHOR";
export const MODALFORM_ADD_CATEGORY = "MODALFORM_ADD_CATEGORY";
export const MODALFORM_EDIT_CATEGORY = "MODALFORM_EDIT_CATEGORY";
export const CLOSE_MODAL = "CLOSE_MODAL";
